#!/usr/bin/env bash
# Fails if anything published to GitHub Pages leaks private-estate detail.
#
# This repo is PUBLIC. The infrastructure it describes is not. The docs here are
# written from scratch rather than copied out of the private repo, precisely so
# there is nothing to scrub — this script asserts that stays true.
#
# Usage: scripts/check-public-docs.sh [path ...]   (default: docs/ examples/ README.md)
#
# GUARD_CONTENT_ONLY=1 runs the leak patterns alone and skips the structural checks
# (nav, stats freshness, stats methods). scripts/gather-stats.py uses it to vet its own
# output before writing it; nothing else should.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
# docs/_data/stats.yml is regenerated by `make stats`; older than this and it is
# stale enough to mislead, so the guard (and the weekly CI run) turns red.
STATS_MAX_AGE_DAYS=21

TARGETS=("$@")
# examples/ was added 2026-08-23 and had to be enrolled here explicitly. That is
# the same shape as a defect this project has hit twice elsewhere: adding a group
# for one purpose does NOT enrol it in the others, and the gap is silent because
# the check still passes — just over less than you think. When adding a directory
# of publishable content, grep for every place the old list is named.
[ ${#TARGETS[@]} -eq 0 ] && TARGETS=(docs examples README.md)

fail=0
report_at() { # <label> <regex> <why> <path ...>
  local label="$1" pattern="$2" why="$3" hits
  shift 3
  # Every rule is case-insensitive (-i): a hostname or a suffix does not stop being one
  # because it was typed in capitals, and the guard must not be beaten by .LOCAL or TS.NET.
  hits=$(grep -rHInEi "$pattern" "$@" 2>/dev/null || true)
  if [ -n "$hits" ] && [ -n "${STRIP:-}" ]; then
    # Blank the allowed substring out of each hit and keep only lines that still match,
    # so an allowed form never shelters a real one on the same line. The file name and
    # line number are dropped first (they are not content), and the text is lower-cased
    # so the allowance is case-insensitive too (${var//x/} is not, in bash 3.2).
    # STRIP may hold several bash glob patterns, one per line.
    local kept="" line content strip
    while IFS= read -r line; do
      content=$(tr '[:upper:]' '[:lower:]' <<<"${line#*:*:}")
      while IFS= read -r strip; do
        [ -n "$strip" ] && content="${content//$strip/}"
      done <<<"$STRIP"
      if grep -qEi "$pattern" <<<"$content"; then kept+="$line"$'\n'; fi
    done <<<"$hits"
    hits="${kept%$'\n'}"
  fi
  if [ -n "$hits" ]; then
    fail=1
    echo "FAIL: $label"
    echo "      $why"
    printf '%s\n' "$hits" | sed 's/^/      /'
    echo
  else
    printf 'ok:   %s\n' "$label"
  fi
}
report() { report_at "$1" "$2" "$3" "${TARGETS[@]}"; } # <label> <regex> <why>

# Tailnet names are publicly resolvable and the Funnel edge is a real public
# endpoint — this is the one that actually matters.
report "tailnet hostnames" \
  '\.ts\.net|tail[0-9a-f]{6,}' \
  "Tailscale names resolve publicly and point at a live edge."

report "credential paths" \
  '\.credentials/|cosign\.key|api-token|api-key|\.env\b' \
  "Names where secrets live are a map for anyone looking."

report "private LAN addresses" \
  '\b(192\.168|10\.(4[0-9]|[0-9])\.|172\.(1[6-9]|2[0-9]|3[01])\.)[0-9.]*|\b10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\b' \
  "RFC1918 addressing (all of 10.0.0.0/8, 172.16/12, 192.168/16) describes the internal topology."

report "fleet hostnames" \
  '\b(delli7c[0-9a-z]*|imaci7g[0-9a-z]*|mbpi[57][0-9a-z]*|rpi[0-9]+[a-z0-9]*|MacStudioM2Max12|MacMiniM2Pro10)\b' \
  "Real machine names; use role descriptions instead."

report "CGNAT / WAN addresses" \
  '\b100\.(6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])\.[0-9]+\.[0-9]+' \
  "Carrier-grade NAT range - identifies the live WAN allocation."

# The machine-generated stats page is the newest way for a private detail to arrive:
# a script copies it out of the live estate, so the patterns below are what stand
# between a registry line and the public site.
# In-cluster DNS (svc.cluster.local) is Kubernetes' own suffix, not a LAN machine.
STRIP=".cluster.local" report "mDNS (.local) names" \
  '\b[A-Za-z0-9][A-Za-z0-9-]*\.local\b' \
  "A .local name is a LAN machine; it is how the private registry is addressed."

# Colon or dash separated, Cisco dotted (aaaa.bbbb.cccc), and bare 12-hex-digit forms. The bare
# form must contain at least one a-f letter, so a 12-digit count (a byte total) is not a MAC, and
# it must not follow a path or name character or an "=" (except "v=", the cache-buster the site
# puts after its image names - "?v=<hash>" is a content hash, not a hardware address).
mac_bare=""
for i in 0 1 2 3 4 5 6 7 8 9 10 11; do
  mac_bare+="${mac_bare:+|}[0-9]{$i}[a-f][0-9a-f]{$((11 - i))}"
done
report "MAC addresses" \
  "\\b([0-9a-f]{2}[:-]){5}[0-9a-f]{2}\\b|\\b[0-9a-f]{4}\\.[0-9a-f]{4}\\.[0-9a-f]{4}\\b|(^|[^0-9a-z_./=-]|[^v]=)($mac_bare)\\b" \
  "A hardware address identifies one physical machine."

# Any dotted host followed by a 4-5 digit port, and any bare IPv4 with a port. Public URLs on
# this site carry no port, so there is no allowance: a figure like host:5000 is a private service.
# In-cluster service DNS with its port (svc.cluster.local:9090) is Kubernetes' own naming.
STRIP=$'.svc.cluster.local:[0-9][0-9][0-9][0-9][0-9]\n.svc.cluster.local:[0-9][0-9][0-9][0-9]' \
report "registry host:port" \
  '\b[a-z0-9][a-z0-9-]*(\.[a-z0-9-]+)+:[0-9]{4,5}\b|\b([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{2,5}\b|\bregistry[a-z0-9-]*:[0-9]{4,5}\b' \
  "A host followed by a port names a private service, usually the image registry."

report "image digests" \
  '\bsha(256|384|512):[0-9a-f]{12,}' \
  "A digest pins one exact private image; publish counts, not digests."

# Shapes of credentials: AWS access key ids, GitHub / GitLab / Slack tokens, API keys in the
# sk- style, JSON web tokens and PEM private key headers.
report "token shapes" \
  '\bAKIA[0-9A-Z]{16}\b|\b(gh[pousr]_|github_pat_)[A-Za-z0-9_]{20,}|\bglpat-[A-Za-z0-9_-]{16,}|\bxox[abprs]-[A-Za-z0-9-]{10,}|\bsk-[A-Za-z0-9_-]{20,}|\beyJ[A-Za-z0-9_-]{8,}\.eyJ[A-Za-z0-9_-]{8,}|-----BEGIN [A-Z ]*PRIVATE KEY' \
  "Looks like a live credential."

# IPv6: full eight-group form, link-local (fe80::), unique-local (fc00::/7, which is what
# Tailscale's fd7a: ULA range is), and a compressed form with at least two groups before the ::.
report "IPv6 addresses" \
  '\b([0-9a-f]{1,4}:){7}[0-9a-f]{1,4}\b|\bf[cd][0-9a-f]{2}:[0-9a-f:]*|\bfe[89ab][0-9a-f]:[0-9a-f:]*|\b([0-9a-f]{1,4}:){2,6}:([0-9a-f]{1,4}\b)?' \
  "An IPv6 address, tailnet ULA ones included, identifies a machine as surely as IPv4."

report "issue-tracker sites" \
  'atlassian\.net' \
  "A tracker subdomain names the account and links to private tickets."

# The prose names these repositories on purpose (index.md, the README). Generated data
# has no reason to, and a name that arrives in docs/_data arrived from a script.
report_at "private repo names in generated data" \
  '[Tt]he(PrintingIn3D|SchultzYocto|Imx8Yocto|RoverPlatform|MowerRetrofit|VideoRover|DroneSwarm)|the-docker-swarm-ai' \
  "docs/_data is written by scripts; repository names belong in prose, chosen by a person." \
  docs/_data

# Jekyll has no native mermaid; each page bootstraps it itself, so a diagram on a
# page without the script ships as raw source and nothing errors.
# Process substitution, not a pipe: a pipe would run the loop in a subshell and lose fail=1.
while IFS= read -r page; do
  if ! grep -q 'mermaid.run' "$page"; then
    echo "FAIL: unrendered mermaid diagram"
    echo "  $page has a mermaid block but no renderer — it will display as raw source."
    fail=1
  fi
done < <(grep -rl '```mermaid' "${TARGETS[@]}" --include='*.md' 2>/dev/null || true)

# check_stats <label> <mode> <why>: ask gather-stats.py (stdlib python, no cluster needed).
check_stats() {
  local label="$1" mode="$2" why="$3" out
  if out=$(python3 "$here/gather-stats.py" --verify "$mode" --max-age-days "$STATS_MAX_AGE_DAYS" --data-dir docs/_data 2>&1); then
    printf 'ok:   %s\n' "$label"
  else
    fail=1
    echo "FAIL: $label"
    echo "      $why"
    printf '      %s\n' "${out//$'\n'/$'\n      '}"
    echo
  fi
}

# The header nav is the only way between pages, so a page missing from it is unreachable.
if [ -z "${GUARD_CONTENT_ONLY:-}" ] && [ -f docs/_data/nav.yml ]; then
  for page in docs/*.md; do
    name=$(basename "$page" .md)
    url="/$name.html"; [ "$name" = index ] && url="/"
    if ! grep -qE "url: $url( |})" docs/_data/nav.yml; then
      echo "FAIL: $page is not in docs/_data/nav.yml - no page links to it from the header."
      fail=1
    fi
  done

  # A number published without a date is a claim; one published long after it was
  # measured is a stale claim. Both fail, with the cure in the message.
  check_stats "stats are fresh (<= ${STATS_MAX_AGE_DAYS} days old)" freshness \
    "Run 'make stats' against the live cluster and commit docs/_data/stats.yml."
  # The page prints a method beside every figure; a figure with none is unexplained.
  check_stats "every stat has a published method" methods \
    "Add or remove the matching entry in docs/_data/stats_methods.yml."
fi

if [ "$fail" -ne 0 ]; then
  echo "Public docs guard FAILED — the above would be published to a public site."
  exit 1
fi
echo
echo "Public docs guard passed for: ${TARGETS[*]}"
